### PR TITLE
Feedback

### PR DESCRIPTION
**Pull request by mo8it**
To start with: You project looks really good already :D

You can merge this PR, but I think that you shouldn't. It is meant as feedback.

Please take a look at the diffs of every commit, not the whole PR. This makes it much easier to understand the changes.

Notes:
- Please use rustfmt by default. You can let your editor format files on save.
- Listen to Clippy. You can make your editor show you Clippy lints as diagnostics.
- You should use `State` instead of `Extension` when possible in Axum.
- It turns out that you don't need to mutate the fields of your state struct because the database takes care of synchronization. This is why I removed `RwLock`. If you add a field later that needs a mutation, you can add `Mutex` or `RwLock` to that field.
- I recommend practicing iterators. As you can see in some of the commits, they can make things a matter of a single line and they have no performance overhead :D
- `dotenvy` is the successor of `dotenv` which isn't maintained anymore: https://github.com/allan2/dotenvy?tab=readme-ov-file#why-does-this-fork-exist
- If you have any questions, don't hesitate to ask :D

### CODE REVIEW

**Comment by Zitronenjoghurt** [comment]
Huge thanks, I will definitely apply this tomorrow^^

I have a few questions:
- What exactly does it mean to "leak" the state?
- When would it be viable to use Extension?

And something not related to the feedback:
Do you know a feasible way of automatically sanitizing the query models on deserialization? I thought about implementing Deserialize myself but it didn't quite work when I tried and let it be like it is rn xD

**Comment by mo8it** [comment]
Leaking the state means that you tell the compiler to not drop it. You allocate some data on the heap using `Box` (but it also works with `Vec` and `String`) and then you leak it to get a static reference `&'static`. It is just a pointer to memory that will not be freed by the program itself. After the program exits, the kernel cleans up and frees this memory.

Why is it useful? You can share a static reference with multiple threads without any issues. If you have a normal reference, then you can't share it with other threads (unless you use scoped threads, but this is not relevant in Axum). Because it is possible that a thread tries to read this reference after the value is dropped in the thread that created it. Normally, you use an `Arc` for such a case. It is an **A**tomic **R**eference **C**ounter. It counts how many references exist to free the memory after the last reference. But if you leak the memory, it doesn't have to be freed and therefore you skip the overhead of the atomic reference counting. This overhead is negligible, but why have it when you can just have a static reference?

Leaking is very useful for things like this app state or also program configuration that live until the program exits.

---

The CHANGELOG of Axum 0.6 says

> We recommend migrating from Extension to State for sharing application state since that is more type safe and faster. That is done by using Router::with_state and State.

In the docs:

> You should prefer using [State](https://docs.rs/axum/latest/axum/extract/struct.State.html) if possible since it’s more type safe. The downside is that it’s less dynamic than request extensions.

Until now, I only needed `State`.  So I can't really say when you would need the more "dynamic" `Extension`. But if you can do the same thing with both, then you should prefer `State`.

---

I don't have experience in MongoDB so I can't help with questions related to it 😅
I only use [SQLx](https://github.com/launchbadge/sqlx) with PostgreSQL.

**Comment by Zitronenjoghurt** [comment]
I am really struggling with the State thingy right now, I tried to search up solutions but nothing really seems to work ._. Whenever I try to pass a Box::leak thingy its mutable for some reason and with_state expects ()

**Comment by Zitronenjoghurt** [comment]
For some reason, not even the example in the official documentation works:
https://github.com/Zitronenjoghurt/lemcom-api/commit/04fdefcb0582a704c1d1afa8bf570179b5b060b8

mismatched types
expected `()`, found `AppState`

Did I overlook something silly?

**Comment by Zitronenjoghurt** [comment]
This might work I think: https://github.com/Zitronenjoghurt/lemcom-api/commit/f1823c7c3b8881a0ed73c2fe0de65b4546578e80

Though then Id have to specify the AppState for every nested router

**Comment by mo8it** [comment]
`Router` is generic over the state type with the default `()` for no state. Whenever you return `Router`, you are actually returning `Router<()>`. So you return `Router<()>` from `resources::ping::router()` and `resources::user::router()`. which means that `with_router` now expects the state that these nested routers expect (which is `()`). You need to tell all handlers to expect that state type first before calling `with_state`.

This is the type safety that `State` provides over `Extension`. If your handlers expect an `Extension` but you don't provide it, then they fail at runtime. With `State`, you get the error at compile time.

About the static reference being mutable: `leak` returns a mutable static reference, but we actually want to have an immutable one. This is often automatically inferred by the compiler, but you can help it when needed by using this:

```rust
let state: &'static _ = Box::leak(Box::new(…));
```

The compiler can then at least infer the underscore.

**Comment by Zitronenjoghurt** [comment]
Thanks for your help^^ I still got a slight problem, the parts.uri.path() does not include the path its nested in, like when I GET /user/search, path will actually just be /search, do you know why that is?

A workaround would be to nest everything at / in main.rs and specify /user in every user endpoint, though there must be a proper solution xD

**Comment by mo8it** [comment]
You need to use `OriginalUri`:

https://docs.rs/axum/latest/axum/extract/struct.OriginalUri.html

**Comment by Zitronenjoghurt** [comment]
I am so lost how to implement that into my current structure, everything I can think of seems overly complicated, like passing it through to the endpoints as a parameter or something 😵‍💫

**Comment by mo8it** [comment]
If you want to add it to the `ExtractUser` implementation of `FromRequestParts`, then you can use `req.extensions().get::<OriginalUri>()` like in this example: https://docs.rs/axum/latest/axum/extract/struct.OriginalUri.html#extracting-via-request-extensions

**Pull request closed without merging**
